#!/usr/bin/env python3

import rospy

if __name__ == "__main__":
    rospy.init_node('counter')
    arr = [0,0,0]
    rospy.sleep(0.5)
    t0 = rospy.get_time()

    while not rospy.is_shutdown():
        t1 = rospy.get_time() - t0
        rospy.loginfo(t1)
        arr[0]+=1
        rospy.loginfo(str(arr))
        rospy.sleep(1)

        if arr == [10,0,0]:
            break

