#!/usr/bin/env python3

import rospy

from geometry_msgs.msg import Twist
from nav_msgs.msg import Odometry

 
class Driver:

    def __init__(self):
        rospy.init_node('undock')
        self.pub = rospy.Publisher('cmd_vel',Twist, queue_size=10)
        rospy.Subscriber('odom', Odometry, self.odomCB)
        self.rate = rospy.Rate(100)
        self.twist = Twist()
        self.driving_speed = 1
        self.driving_speed_slow = 0.2
        self.driving_speed_approach = 0.025
        self.current_x = 0.0
        self.goal = 2
        rospy.loginfo(self.goal)


    def run(self):
        while not rospy.is_shutdown():
            rospy.wait_for_message('/odom', Odometry)
            self.initial_x = self.current_x
            
            distance_driven = 0
            
            while distance_driven<self.goal:
                
                if self.goal-distance_driven>0.3:
                    self.twist.linear.x = self.driving_speed
                elif 0.3>=self.goal-distance_driven>0.05:
                    self.twist.linear.x = self.driving_speed_slow
                elif self.goal-distance_driven<=0.05:
                    self.twist.linear.x = self.driving_speed_approach
                
                self.pub.publish(self.twist)
                distance_driven = self.current_x - self.initial_x
                
                rospy.loginfo(distance_driven)
                self.rate.sleep()   

            self.twist.linear.x = 0
            self.pub.publish(self.twist)  
            break   

    def odomCB(self,msg):        
        self.current_x = msg.pose.pose.position.x
             

if __name__ == "__main__":
    d = Driver()
    d.run()
